---
title: "PRIMR vignette"
author: "Theo Botella"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PRIMR Pipeline}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo=TRUE
)

```

This vignette explain how to use PRIMR

# Overview

1. runPRIMR 
2. Genreate Counts Matrix

## Load PRIMR

```{r, eval = TRUE}
library(PRIMR)

library(dplyr)
library(reshape2)
library(ggplot2)
```


## Inputs

```{r, eval = TRUE}
out='/gpfs/commons/home/tbotella/missionbio/primr_package/data'
bamfile='/gpfs/commons/home/tbotella/missionbio/primr_package/data/datatest.bam'
ampfile='/gpfs/commons/home/tbotella/missionbio/primr_package/data/ampliconsPanel.txt'
sample.id='Sample1'
nthreads=40
```


## runPRIMR 

```{r, eval = TRUE}
runPRIMR(out=out, bamfile=bamfile, ampfile=ampfile,sample.id=sample.id,nthreads=nthreads)
```


## countReads

```{r, eval = TRUE}
qnames.path=paste0(out,'/',sample.id,'/filtered_qnames/qnames_',sample.id,'.txt')
format='seurat'

countReads(out=out, qnames.path=qnames.path, sample.id=sample.id, format=format)
```

